apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-lg
spec:
  template:
    metadata:
      labels:
        app: cockroachdb-lg
    spec:
      restartPolicy: Never
      containers:
      - name: cockroachdb-lg
        image: cockroachdb/loadgen-kv:0.1
        imagePullPolicy: IfNotPresent
        command:
          - "/kv"
          - "--duration"
          - "time_duration"
          - "postgres://root@svc_namespace.svc_name.svc.cluster.local:26257/kv?sslmode=disable"
