---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-percona
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
   
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: ranjnshashank855/percona-installer
        imagePullPolicy: Always

        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: actionable
 
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./percona/percona-installer.yaml -i /etc/ansible/hosts -v; exit 0"]
        
