# TODO 
# Apply openebs operator and openebs storage class

- hosts: localhost
  connection: local

  vars_files:
  - vars.yaml

  tasks:
    - block:

          - name: Downloading openebs-operator.yaml
            get_url:
              url: "{{ openebs_operator_link }}"
              dest: "{{ playbook_dir }}/openebs-operator.yaml"


          - name: Updating maya api server image
            replace:
              path: "openebs-operator.yaml"
              regexp: "image: openebs/m-apiserver.*"
              replace: "image: {{ lookup('env','MAYA_APISERVER_IMAGE') }}"
            when: lookup('env','MAYA_APISERVER_IMAGE') | length > 0

          - name: Updating openebs provisioner image
            replace:
              path: "openebs-operator.yaml"
              regexp: "image: openebs/openebs-k8s-provisioner.*"
              replace: "image: {{ lookup('env','OPENEBS_PROVISIONER_IMAGE') }}"
            when: lookup('env','OPENEBS_PROVISIONER_IMAGE') | length > 0

          - name: Updating openebs snapshot controller image
            replace:
              path: "openebs-operator.yaml"
              regexp: "image: openebs/snapshot-controller.*"
              replace: "image: {{ lookup('env','OPENEBS_SNAPSHOT_CONTROLLER_IMAGE') }}"
            when: lookup('env','OPENEBS_SNAPSHOT_CONTROLLER_IMAGE') | length > 0

          - name: Updating openebs snapshot provisioner image
            replace:
              path: "openebs-operator.yaml"
              regexp: "image: openebs/snapshot-provisioner.*"
              replace: "image: {{ lookup('env','OPENEBS_SNAPSHOT_PROVISIONER_IMAGE') }}"
            when: lookup('env','OPENEBS_SNAPSHOT_PROVISIONER_IMAGE') | length > 0

          - name: Applying openebs operator
            shell: "{{ kubeapply }} apply -f {{ openebs_operator }}" 
            args:
              executable: /bin/bash
    
          - name: Checking Maya-API-Server is running
            shell: kubectl get pods -n {{ namespace }} -o jsonpath='{.items[?(@.metadata.labels.name=="maya-apiserver")].status.phase}'
            register: maya_api
            until: "'Running' in maya_api.stdout"
            delay: 30
            retries: 100

          - name: Checking OpenEBS-provisioner is running
            shell: kubectl get pods -n {{ namespace }} -o jsonpath='{.items[?(@.metadata.labels.name=="openebs-provisioner")].status.phase}'
            register: openebs_prob
            until: "'Running' in openebs_prob.stdout"
            delay: 30
            retries: 100

          - name: Get maya-apiserver pod name
            shell: kubectl get pods -n {{ namespace }} --selector=name=maya-apiserver
            args:
              executable: /bin/bash
            register: result_name

          - name: Create fact for pod name
            set_fact: 
              pod_name: "{{ result_name.stdout_lines[1].split()[0] }}"

          - name: Checking OpenEBS-Snapshot-Operator is running
            shell: kubectl get pods -n {{ namespace }} -o jsonpath='{.items[?(@.metadata.labels.name=="openebs-snapshot-operator")].status.phase}'
            register: oso
            until: "'Running' in oso.stdout"
            delay: 30
            retries: 100

          - name: Confirm that maya-cli is available in the maya-apiserver pod
            shell: kubectl exec {{pod_name}} -c maya-apiserver -n {{ namespace }} -- mayactl version
            args:
              executable: /bin/bash
            register: result_vers
            failed_when: "'m-apiserver status:  running' not in result_vers.stdout"
          
          - set_fact:
              flag: "Pass"
      rescue: 
        - set_fact: 
            flag: "Fail"
