# TODO 
# Delete openebs operator

- hosts: localhost
  connection: local

  vars_files:
  - vars.yaml

  tasks:
    - block:
          - name: Cleaning openebs operator
            shell: "{{ kubeapply }} delete -f {{ openebs_operator_link }}" 
            args:
              executable: /bin/bash
            ignore_errors: True

          - name: Confirm pods has been deleted
            shell: "kubectl get pods --all-namespaces"
            args:
              executable: /bin/bash
            register: result
            until: ' item not in result.stdout'
            with_items:
              - "maya-apiserver"
              - "openebs-provisioner"
              - "openebs-snapshot-operator"
            delay: 30
            retries: 100

          - name: Confirm that namspace has been deleted
            shell: 'kubectl get namespaces'
            args:
              executable: /bin/bash
            register: result
            until: '"namespace" not in result.stdout'
            delay: 30
            retries: 100

          - set_fact:
              flag: "Pass"
      rescue: 
        - set_fact: 
            flag: "Fail"
