---
- hosts: localhost
  gather_facts: yes

  vars: 
    testfile: "{{ playbook_dir }}/tests.out"

  tasks:

    - name: Clear existing test lists 
      file: 
        path: "{{ testfile }}"
        state: absent 
 
    - name: Obtain list of Kubernetes test job specifications 
      include: utils/getFiles.yaml
        dir="{{ litmus_dir }}/apps/{{ item }}/tests"
        expr="^run_litmus"
        tfile="{{ testfile }}"
      with_items: "{{ application }}"

    - name: Run the Kubernetes test jobs on selected storage providers 
      include: utils/runTest.yaml 
      with_lines: cat {{ testfile }}
