---
- name: Obtain list of Kubernetes test job specifications
  find:
    paths: "{{ dir }}"
    patterns: "{{ expr }}"
    recurse: yes
    use_regex: yes
  register: result

- debug: 
    msg: "{{ item.path }}"
  with_items: "{{ result.files }}" 

- name: Create test path list
  lineinfile: 
    path: "{{ tfile }}"
    line: "{{ item.path }}"
    state: present
    create: yes
  with_items: "{{ result.files }}"

