---
#########################################
# Ansible Runtime Specifications        #
#########################################

#Provider storage class
#Supported providers(openebs, local-pv)
storage_class: openebs-standard

#Option to enable slack notifications to specified channel
#Accepted entries(true, false): default:true
slack_notify: true

#Select the desired application
#Supported applications(percona, tba, all) 
application:
  - percona
  - fio

litmus_dir: "{{ ansible_env.HOME }}/git/litmus" 

