# Description:  Deletes the Virtual Private Cloud with the name openebs-e2e, runs when all e2e test
# are finished running 
# Author: Harshvardhan Karn
###############################################################################################
#Steps:
#1. Delete the routes(if exists) and VPC , openebs-e2e in Google Cloud
###############################################################################################

---
- hosts: localhost
  tasks:
       - block:
           - name: Deleting Routes, if exists
             shell: gcloud compute routes delete $(gcloud compute routes list --filter="network:{{ vpc_name }}"  --format="get(name)") -q
             ignore_errors: yes
           - name: Deleting VPC
             shell: gcloud compute --project={{ project }} networks delete {{ vpc_name }} -q 
           - name: Test Passed
             set_fact:
               flag: "Test Passed"
         rescue:
             - name: Test Failed
               set_fact:
                 flag: "Test Failed"
