# Description:  Deletes the Virtual Private Cloud with the name openebs-e2e, runs when all e2e test
# are finished running 
# Author: Harshvardhan Karn
###############################################################################################
#Steps:
#1. Delete the routes(if exists) and VPC , openebs-e2e in Google Cloud
###############################################################################################

---
- hosts: localhost
  vars_files:
    - gcp-vars.yml
  tasks:
       - block:
             - block:
                 - name: Deleting VPC `openebs-e2e`
                   shell: gcloud compute routes delete $(gcloud compute routes list --filter="name:openebs AND network:openebs-e2e"  --format="get(name)") -q || gcloud compute --project=openebs-ci networks delete openebs-e2e -q
               rescue:
                 - name: Only VPC
                   shell: gcloud compute --project=openebs-ci networks delete openebs-e2e -q 
             - name: Test Passed
               set_fact:
                 flag: "Test Passed"
         rescue:
             - name: Test Failed
               set_fact:
                 flag: "Test Failed"
